const shoppingList = [
  {
    id: "sub01",
    category: "IK 시리즈",
    name: "SNOWMAN15 Portable Stand 3Colors",
    price: 110000,
    src: "./images/sub_01.jpg",
    best: "BEST",
  },
  {
    id: "sub02",
    category: "IK 시리즈",
    name: "SNOWMAN22 Table Stand Butter",
    price: 220000,
    src: "./images/sub_02.jpg",
    best: "BEST",
  },
  {
    id: "sub03",
    category: "IK 시리즈",
    name: "SNOWMAN22 Floor Stand Butter",
    price: 340000,
    src: "./images/sub_03.jpg",
    best: "BEST",
  },
  {
    id: "sub04",
    category: "IK 시리즈",
    name: "FROG38 Pendant 5Colors",
    price: 120000,
    src: "./images/sub_04.jpg",
    best: false,
  },
  {
    id: "sub05",
    category: "IK 시리즈",
    name: "SNOWMAN22 SOLID Table Stand All Butter",
    price: 230000,
    src: "./images/sub_05.jpg",
    best: false,
  },

  {
    id: "sub06",
    category: "IK 시리즈",
    name: "TEACUP 4A Table Stand 3Colors",
    price: 75000,
    src: "./images/sub_06.jpg",
    best: false,
  },

  {
    id: "sub07",
    category: "IK 시리즈",
    name: "CANDLE9 Table Stand 5Colors",
    price: 55000,
    src: "./images/sub_07.jpg",
    best: false,
  },
  {
    id: "sub08",
    category: "IK 시리즈",
    name: "SNOWMAN22 SOLID Table Stand 29CM Edition",
    price: 230000,
    src: "./images/sub_08.jpg",
    best: false,
  },

  {
    id: "sub09",
    category: "IK 시리즈",
    name: "TALLBOY16 Table Stand 6Colors",
    price: 180000,
    src: "./images/sub_09.jpg",
    best: false,
  },

  {
    id: "sub10",
    category: "IK 시리즈",
    name: "ACORN22 Table Stand 5Colors",
    price: 160000,
    src: "./images/sub_10.jpg",
    best: false,
  },

  {
    id: "sub11",
    category: "IK 시리즈",
    name: "NEST25 Pendant 2Colors",
    price: 120000,
    src: "./images/sub_11.jpg",
    best: false,
  },
  {
    id: "sub12",
    category: "IK 시리즈",
    name: "FONDUE16 Table Stand KYOBO BOOK Edition 2Colors",
    price: 280000,
    src: "./images/sub_12.jpg",
    best: false,
  },
  {
    id: "sub13",
    category: "IK 시리즈",
    name: "SNOWMAN22 SOLID Table Stand 2Colors",
    price: 230000,
    src: "./images/sub_13.jpg",
    best: false,
  },
  {
    id: "sub14",
    category: "IK 시리즈",
    name: "WOOD3 Table Stand 3Colors",
    price: 55000,
    src: "./images/sub_14.jpg",
    best: false,
  },
  {
    id: "sub15",
    category: "IK 시리즈",
    name: "ACORN22 Floor Stand 5Colors",
    price: 270000,
    src: "./images/sub_15.jpg",
    best: false,
  },

  {
    id: "sub16",
    category: "IK 시리즈",
    name: "FROG22 Table Stand 5Colors",
    price: 160000,
    src: "./images/sub_16.jpg",
    best: false,
  },
  {
    id: "sub17",
    category: "IK 시리즈",
    name: "SNOWMAN22 Table Stand 2Colors",
    price: 220000,
    src: "./images/sub_17.jpg",
    best: false,
  },
  {
    id: "sub18",
    category: "IK 시리즈",
    name: "SATURN55 SMART Pendant 2Colors",
    price: 240000,
    src: "./images/sub_18.jpg",
    best: false,
  },
  {
    id: "sub19",
    category: "IK 시리즈",
    name: "SNOWBALL22 Table Stand 2Colors",
    price: 200000,
    src: "./images/sub_19.jpg",
    best: false,
  },
  {
    id: "sub20",
    category: "IK 시리즈",
    name: "FROG22 Pendant 5Colors",
    price: 95000,
    src: "./images/sub_20.jpg",
    best: "BEST",
  },
  {
    id: "sub21",
    category: "IK 시리즈",
    name: "ACORN22 Pendant 5Colors",
    price: 95000,
    src: "./images/sub_21.jpg",
    best: "BEST",
  },
  {
    id: "sub22",
    category: "IK 시리즈",
    name: "SLOPE45 SMART Pendant 3Colors",
    price: 290000,
    src: "./images/sub_22.jpg",
    best: "BEST",
  },
  {
    id: "sub23",
    category: "IK 시리즈",
    name: "SNOWBALL22 Floor Stand Butter",
    price: 320000,
    src: "./images/sub_23.jpg",
    best: "BEST",
  },
  {
    id: "sub24",
    category: "IK 시리즈",
    name: "SWAN2 Floor Stand ODENSE Edition",
    price: 340000,
    src: "./images/sub_24.jpg",
    best: false,
  },
  {
    id: "sub25",
    category: "IK 시리즈",
    name: "MAGRITTE25 Pendant 4Colors",
    price: 280000,
    src: "./images/sub_25.jpg",
    best: false,
  },

  {
    id: "sub26",
    category: "IK 시리즈",
    name: "ACORN38 Pendant 5Colors",
    price: 120000,
    src: "./images/sub_26.jpg",
    best: false,
  },

  {
    id: "sub27",
    category: "IK 시리즈",
    name: "AMBER22 Pendant",
    price: 150000,
    src: "./images/sub_27.jpg",
    best: false,
  },
  {
    id: "sub28",
    category: "IK 시리즈",
    name: "WOOD2 Table Stand 2Colors",
    price: 55000,
    src: "./images/sub_28.jpg",
    best: false,
  },
  {
    id: "sub29",
    category: "IK 시리즈",
    name: "CORE4.5 Pendant 4Colors",
    price: 60000,
    src: "./images/sub_29.jpg",
    best: false,
  },

  {
    id: "sub30",
    category: "IK 시리즈",
    name: "일광전구 : 빛을 만들다 (60년 된 전구 회사는 어떻게 리브랜딩에 성공했나)",
    price: 18000,
    src: "./images/sub_30.jpg",
    best: false,
  },

  {
    id: "sub31",
    category: "IK 시리즈",
    name: "디밍 LED G80 White (전구색, E26)",
    price: 4850,
    src: "./images/sub_31.jpg",
    best: false,
  },
  {
    id: "sub32",
    category: "IK 시리즈",
    name: "F-LED D110 (전구색, E26)",
    price: 13000,
    src: "./images/sub_32.jpg",
    best: false,
  },
  {
    id: "sub33",
    category: "IK 시리즈",
    name: "SNOWBALL22 Table Stand Butter",
    price: 200000,
    src: "./images/sub_33.jpg",
    best: false,
  },
  {
    id: "sub34",
    category: "IK 시리즈",
    name: "SNOWBALL22 SOLID Table Stand 2Colors",
    price: 210000,
    src: "./images/sub_34.jpg",
    best: false,
  },
  {
    id: "sub35",
    category: "IK 시리즈",
    name: "TEACUP R Table Stand 2Colors",
    price: 75000,
    src: "./images/sub_35.jpg",
    best: false,
  },

  {
    id: "sub36",
    category: "IK 시리즈",
    name: "클래식 ST64 (전구색, E26)",
    price: 6500,
    src: "./images/sub_36.jpg",
    best: false,
  },
  {
    id: "sub37",
    category: "IK 시리즈",
    name: "SNOWBALL22 Floor Stand 2Colors",
    price: 320000,
    src: "./images/sub_37.jpg",
    best: false,
  },
  {
    id: "sub38",
    category: "IK 시리즈",
    name: "SNOWMAN22 Floor Stand 2Colors",
    price: 340000,
    src: "./images/sub_38.jpg",
    best: false,
  },
  {
    id: "sub39",
    category: "IK 시리즈",
    name: "WOOD2 SHADE Table Stand 2Colors",
    price: 65000,
    src: "./images/sub_39.jpg",
    best: false,
  },
  {
    id: "sub40",
    category: "IK 시리즈",
    name: "TRIANGLE120 C Pendant 2Colors",
    price: 360000,
    src: "./images/sub_40.jpg",
    best: "BEST",
  },

  {
    id: "sub41",
    category: "IK 시리즈",
    name: "APOLLO22 Table Stand 2Colors",
    price: 340000,
    src: "./images/sub_41.jpg",
    best: false,
  },
  {
    id: "sub42",
    category: "IK 시리즈",
    name: "FROG22 Floor Stand 5Colors",
    price: 270000,
    src: "./images/sub_42.jpg",
    best: false,
  },
  {
    id: "sub43",
    category: "IK 시리즈",
    name: "SNOWBALL22 SOLID Table Stand All Butter",
    price: 210000,
    src: "./images/sub_43.jpg",
    best: false,
  },
  {
    id: "sub44",
    category: "IK 시리즈",
    name: "TEACUP 4R Table Stand",
    price: 75000,
    src: "./images/sub_44.jpg",
    best: false,
  },
  {
    id: "sub45",
    category: "IK 시리즈",
    name: "FROG38 Floor Stand 5Colors",
    price: 310000,
    src: "./images/sub_45.jpg",
    best: false,
  },

  {
    id: "sub46",
    category: "IK 시리즈",
    name: "ACORN38 Floor Stand 5Colors",
    price: 310000,
    src: "./images/sub_46.jpg",
    best: false,
  },
  {
    id: "sub47",
    category: "IK 시리즈",
    name: "SWAN2 Table Stand ODENSE Edition 3Colors",
    price: 240000,
    src: "./images/sub_47.jpg",
    best: false,
  },
  {
    id: "sub48",
    category: "IK 시리즈",
    name: "PINOCCHIO120 B Pendant 3Colors",
    price: 280000,
    src: "./images/sub_48.jpg",
    best: false,
  },
  {
    id: "sub49",
    category: "IK 시리즈",
    name: "WORKSHOP18 Pendant 3Colors",
    price: 120000,
    src: "./images/sub_49.jpg",
    best: false,
  },
  {
    id: "sub50",
    category: "IK 시리즈",
    name: "SWAN Table Stand ODENSE Edition",
    price: 240000,
    src: "./images/sub_50.jpg",
    best: "BEST",
  },
];

export default shoppingList; //import - export